import time
import typing as T
from abc import ABC, abstractmethod
from dataclasses import dataclass

from pydantic import BaseModel, ConfigDict

CT = T.TypeVar("CT", bound="ActionConfig")
OT = T.TypeVar("OT")


@dataclass
class MoveCommand:
    """
    Move command interface.

    Parameters
    ----------
    dx : float
        Distance to move in the x direction.
    yaw : float
        Yaw angle to turn.
    start_x : float
        Starting x position.
    start_y : float
        Starting y position.
    turn_complete : bool
        Whether the turn is complete.
    speed : float
        Speed of movement.
    """

    dx: float
    yaw: float
    start_x: float = 0.0
    start_y: float = 0.0
    turn_complete: bool = False
    speed: float = 0.5


class ActionConfig(BaseModel):
    """
    Configuration class for Action implementations.
    """

    model_config = ConfigDict(extra="allow")


class ActionConnector(ABC, T.Generic[CT, OT]):
    """
    A connector responsible for forwarding action outputs
    to the execution layer (robot, simulator, etc.).
    """

    def __init__(self, config: CT):
        """
        Initialize the ActionConnector.

        Parameters
        ----------
        config : CT
            Configuration for the action connector.
        """
        self.config: CT = config

    @abstractmethod
    async def connect(self, output: OT) -> None:
        """
        Connect the action output to the execution backend.

        Parameters
        ----------
        output : OT
            The output generated by the action.
        """
        raise NotImplementedError

    def tick(self) -> None:
        """
        Optional periodic hook for connectors.
        """
        time.sleep(60)


@dataclass
class AgentAction:
    """
    Base class for agent actions.

    Parameters
    ----------
    name : str
        The name of the action.
    llm_label : str
        The label used by the LLM for this action.
    interface : type
        Input/output interface type used by the action.
    connector : ActionConnector
        Connector handling execution of the action.
    exclude_from_prompt : bool
        Whether to exclude this action from LLM prompting.
    """

    name: str
    llm_label: str
    interface: type
    connector: ActionConnector
    exclude_from_prompt: bool = False
