"""Env command - Manage environment variables."""

import os
from pathlib import Path
from typing import Optional

import typer
from rich.table import Table

from cli.utils.output import console, print_error, print_info, print_success

# Template for .env.example
ENV_TEMPLATE = """# OM1 Environment Configuration
# Copy this file to .env and fill in your values
# Generated by: om1 env generate

# ===================
# REQUIRED (for most configs)
# ===================
OM_API_KEY=your_openmind_api_key_here

# ===================
# LLM PROVIDERS (choose one based on your config)
# ===================
# OpenAI (for open_ai.json5, conversation.json5)
OPENAI_API_KEY=sk-...

# Google Gemini (for gemini.json5)
GOOGLE_API_KEY=

# DeepSeek (for deepseek.json5)
DEEPSEEK_API_KEY=

# xAI Grok (for grok.json5)
XAI_API_KEY=

# OpenRouter (for openrouter.json5)
OPENROUTER_API_KEY=

# Ollama (for ollama.json5) - No API key needed, just run: ollama serve

# ===================
# SPEECH SERVICES
# ===================
# ElevenLabs TTS (for text-to-speech output)
ELEVENLABS_API_KEY=

# ===================
# INTEGRATIONS
# ===================
# Twitter (for twitter.json5)
TWITTER_API_KEY=
TWITTER_API_SECRET=
TWITTER_ACCESS_TOKEN=
TWITTER_ACCESS_SECRET=

# DIMO/Tesla (for tesla.json5)
DIMO_CLIENT_ID=
DIMO_API_KEY=

# Coinbase CDP (for wallet configs)
CDP_API_KEY=

# ===================
# ROBOTICS
# ===================
ROBOT_IP=192.168.0.241
URID=default
"""

# Known environment variables
KNOWN_ENV_VARS = [
    "OM_API_KEY",
    "OPENAI_API_KEY",
    "GOOGLE_API_KEY",
    "DEEPSEEK_API_KEY",
    "XAI_API_KEY",
    "OPENROUTER_API_KEY",
    "ELEVENLABS_API_KEY",
    "TWITTER_API_KEY",
    "TWITTER_API_SECRET",
    "TWITTER_ACCESS_TOKEN",
    "TWITTER_ACCESS_SECRET",
    "DIMO_CLIENT_ID",
    "DIMO_API_KEY",
    "CDP_API_KEY",
    "ROBOT_IP",
    "URID",
]


def env(
    action: str = typer.Argument(
        ...,
        help="Action: list, get, set, generate, validate",
    ),
    key: Optional[str] = typer.Argument(
        None,
        help="Environment variable name (for get/set).",
    ),
    value: Optional[str] = typer.Argument(
        None,
        help="Value to set (for set action).",
    ),
) -> None:
    """
    Manage OM1 environment variables.

    Actions:
      - list: Show all OM1-related environment variables
      - get KEY: Get value of specific variable
      - set KEY VALUE: Set variable in .env file
      - generate: Create .env.example template
      - validate: Check all required variables are set

    Examples
    --------
        om1 env list
        om1 env get OPENAI_API_KEY
        om1 env set OPENAI_API_KEY sk-...
        om1 env generate
        om1 env validate
    """
    action = action.lower()

    if action == "list":
        _env_list()
    elif action == "get":
        if not key:
            print_error("Please specify a key: om1 env get KEY")
            raise typer.Exit(1)
        _env_get(key)
    elif action == "set":
        if not key or not value:
            print_error("Please specify key and value: om1 env set KEY VALUE")
            raise typer.Exit(1)
        _env_set(key, value)
    elif action == "generate":
        _env_generate()
    elif action == "validate":
        _env_validate()
    else:
        print_error(f"Unknown action: {action}")
        console.print("Valid actions: list, get, set, generate, validate")
        raise typer.Exit(1)


def _env_list() -> None:
    """List all OM1-related environment variables."""
    table = Table(title="OM1 Environment Variables", show_header=True)
    table.add_column("Variable", style="cyan")
    table.add_column("Status")
    table.add_column("Value")

    for var in KNOWN_ENV_VARS:
        value = os.environ.get(var, "")
        if value:
            # Mask sensitive values
            if "KEY" in var or "SECRET" in var or "TOKEN" in var:
                if len(value) > 8:
                    display_value = value[:4] + "..." + value[-4:]
                else:
                    display_value = "***"
            else:
                display_value = value
            status = "[green]Set[/green]"
        else:
            display_value = "[dim]Not set[/dim]"
            status = "[dim]Empty[/dim]"

        table.add_row(var, status, display_value)

    console.print(table)


def _env_get(key: str) -> None:
    """Get value of specific environment variable."""
    value = os.environ.get(key, "")
    if value:
        console.print(f"{key}={value}")
    else:
        print_info(f"{key} is not set")


def _env_set(key: str, value: str) -> None:
    """Set environment variable in .env file."""
    env_path = Path(".env")

    # Read existing content
    existing_lines = []
    key_found = False

    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                if line.strip().startswith(f"{key}="):
                    existing_lines.append(f"{key}={value}\n")
                    key_found = True
                else:
                    existing_lines.append(line)

    # Add new key if not found
    if not key_found:
        existing_lines.append(f"{key}={value}\n")

    # Write back
    with open(env_path, "w") as f:
        f.writelines(existing_lines)

    print_success(f"Set {key} in .env")
    print_info("Restart your shell or run 'source .env' to apply changes")


def _env_generate() -> None:
    """Generate .env.example template."""
    env_example_path = Path(".env.example")

    if env_example_path.exists():
        overwrite = typer.confirm(".env.example already exists. Overwrite?")
        if not overwrite:
            print_info("Cancelled")
            return

    env_example_path.write_text(ENV_TEMPLATE)
    print_success("Created .env.example")
    print_info("Copy to .env and fill in your values: cp .env.example .env")


def _env_validate() -> None:
    """Validate required environment variables."""
    # Core required
    core_vars = ["OM_API_KEY"]

    missing = []
    set_vars = []

    for var in core_vars:
        value = os.environ.get(var, "")
        if value and value not in ("", "your_openmind_api_key_here"):
            set_vars.append(var)
        else:
            missing.append(var)

    if missing:
        console.print("[red]Missing required variables:[/red]")
        for var in missing:
            console.print(f"  - {var}")
        console.print("\nRun [cyan]om1 env generate[/cyan] to create .env.example")
        raise typer.Exit(1)

    print_success("All required environment variables are set")

    # Check optional vars
    optional_set = 0
    for var in KNOWN_ENV_VARS:
        if var not in core_vars and os.environ.get(var, ""):
            optional_set += 1

    if optional_set > 0:
        print_info(f"{optional_set} optional variables configured")
