name: Run Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev pkg-config libfaiss-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Cache zenoh-c
        uses: actions/cache@v4
        with:
          path: .zenoh-c
          key: ${{ runner.os }}-zenoh-c-1.9.0
          restore-keys: |
            ${{ runner.os }}-zenoh-c-

      - name: Download zenoh-c
        run: make download-zenohc

      - name: Run unit tests
        run: make test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: false
